### PR TITLE
remove fits2fits option as it is deprecated in astrometry.net

### PR DESCRIPTION
**Pull request by ubutnux**

### CODE REVIEW

**Comment by vterron** [comment]
We should comment the flag entirely, not only comment it out. I see that [it was removed in Nov 22, 2016](https://github.com/dstndstn/astrometry.net/issues/100), making it the default. We could check the installed Astrometry.net version and still use the flag for older versions.

**Comment by javierblasco** [comment]
Not worth checking, imo. The flag is gone for two years, now. We can raise an error saying that the astrometry is out of date... it's astrometry.net, not iraf... it's easy to update :p

**Comment by vterron** [comment]
Sounds good! Let's raise the error instead, in the same way we have [`SExtractorUpgradeRequired`](https://github.com/vterron/lemon/blob/d60576bec2ad5d1d5043bcb3111dff1fcb58a8d6/astromatic.py#L49-L51).

**Comment by vterron** [comment]
Done in b7a0d34 and 5166da9.

**Pull request closed without merging**
